Q1

In [1]:
# tensor ma matrix hoy ne enu data type same hoy of all the data 
# that is included in the tensor, it is a matrix which is multi-dimensional
# tensor is created from a list
import torch
lis = [[0.1, 0.2, 3.121221], [9, 2.3, 21], [1.2, 32.1, 2]]
tens = torch.tensor(lis)
print(tens)

print("Data type:", tens.dtype) 
# even if i increase the number of decimal places, still it shows float32

tens2 = torch.tensor(lis, dtype=torch.float64)
print(tens2)
print("Data type:", tens2.dtype)

tensor([[ 0.1000,  0.2000,  3.1212],
        [ 9.0000,  2.3000, 21.0000],
        [ 1.2000, 32.1000,  2.0000]])
Data type: torch.float32
tensor([[ 0.1000,  0.2000,  3.1212],
        [ 9.0000,  2.3000, 21.0000],
        [ 1.2000, 32.1000,  2.0000]], dtype=torch.float64)
Data type: torch.float64


In [2]:
# change karva mate normal aj che
print("Before change:", tens[0][1])

tens[0][1] = 9.9999
print("After change:", tens[0][1])

# another way to access
print(tens[0])

Before change: tensor(0.2000)
After change: tensor(9.9999)
tensor([0.1000, 9.9999, 3.1212])


In [3]:
# now auto_grad is the thing which helps in backpropagation automatically
x = torch.tensor(5.2, requires_grad=True)
y = x ** 3
z = y * 1 + 2 
h = x ** 4
h.backward()
print("Gradient at x=5.2 for h is:", x.grad)  
z.backward()
print("Gradient at x=5.2 for z is:", x.grad) 

# i got to know that the gradients can be calculated only for scalar values

Gradient at x=5.2 for h is: tensor(562.4319)
Gradient at x=5.2 for z is: tensor(643.5519)


In [4]:
# arithmetic is simple
ten1 = [1,2,30]
ten2 = [4,5,6]

tensor_ten1 = torch.tensor(ten1)
tensor_ten2 = torch.tensor(ten2)
print("Addition:", tensor_ten1 + tensor_ten2)
print("Subtraction:", tensor_ten1 - tensor_ten2)
print("Multiplication:", tensor_ten1 * tensor_ten2)
print("Division:", tensor_ten1 / tensor_ten2)

wew = [[1,2,3],[4,5,6],[7,8,9]]
wew2 = [[9,8,7],[6,5,4],[3,2,1]]
tensor_wew1 = torch.tensor(wew)
tensor_wew2 = torch.tensor(wew2)
print("Matrix Addition:\n", tensor_wew1 + tensor_wew2)
print("Matrix Subtraction:\n", tensor_wew1 - tensor_wew2)   
print("Matrix Multiplication:\n", tensor_wew1 * tensor_wew2)
print("Matrix Division:\n", tensor_wew1 / tensor_wew2)

Addition: tensor([ 5,  7, 36])
Subtraction: tensor([-3, -3, 24])
Multiplication: tensor([  4,  10, 180])
Division: tensor([0.2500, 0.4000, 5.0000])
Matrix Addition:
 tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])
Matrix Subtraction:
 tensor([[-8, -6, -4],
        [-2,  0,  2],
        [ 4,  6,  8]])
Matrix Multiplication:
 tensor([[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]])
Matrix Division:
 tensor([[0.1111, 0.2500, 0.4286],
        [0.6667, 1.0000, 1.5000],
        [2.3333, 4.0000, 9.0000]])


In [5]:
# Only floating-point tensors can require gradients
# it builds a dag during forward pass
x1 = torch.tensor(2.0, requires_grad=True)
y1 = x1 ** 2

print(y1.grad_fn) 

In [6]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
z = y + 5
z.backward()
print("Gradient at x=3.0 is:", x.grad)
print(y.retain_grad())

# in place operations break gradient tracking
# autograd only stores gradients for leaf tensors.


Gradient at x=3.0 is: tensor(6.)
None


In [7]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
y.retain_grad()
z = y + 5

z.backward()

print("dz/dx:", x.grad)
print("dz/dy:", y.grad)

dz/dx: tensor(6.)
dz/dy: tensor(1.)


Q2

In [8]:
import tensorflow as tf

# tf ma constant and Variable lakhvu pade, if variable hoy to change karay like weights
a = tf.constant(3.0)
v = tf.constant([1.0, 2.0, 3.0])
M = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])

print("v + v:", v + v)
print("M * scalar:\n", M * 2)
print("element ops:\n", tf.square(M))

v + v: tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32)
M * scalar:
 tf.Tensor(
[[2. 4.]
 [6. 8.]], shape=(2, 2), dtype=float32)
element ops:
 tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float32)


In [9]:
A = tf.constant([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0]])

B = tf.constant([[1.0, 2.0],
                 [3.0, 4.0],
                 [5.0, 6.0]])

C = tf.matmul(A, B) # main yaad rakhvanu e ke not like pytorch, tensorflow ma matrix multiplication mate alag function che
# it can't be done by simply A * B
A_T = tf.transpose(A)

print("A x B:\n", C)
print("Transpose of A:\n", A_T)

A x B:
 tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)
Transpose of A:
 tf.Tensor(
[[1. 4.]
 [2. 5.]
 [3. 6.]], shape=(3, 2), dtype=float32)


In [10]:
M = tf.constant([[4.0, 7.0],
                 [2.0, 6.0]])

b = tf.constant([[5.0],
                 [5.0]])

# solve kare Ax = b
x = tf.linalg.solve(M, b)
# symmetric matrix ma real value result kare
eigen_vals, eigen_vecs = tf.linalg.eigh(M)
 
l2_norm = tf.norm(M, ord=2)

# shape ne dtype evu badhu nai print karava mate
print("Solution of Ax=b:\n", x.numpy())
print("Eigenvalues:", eigen_vals.numpy())
print("Eigenvectors:\n", eigen_vecs.numpy())
print("L2 norm:", l2_norm.numpy())

Solution of Ax=b:
 [[-0.49999988]
 [ 0.99999994]]
Eigenvalues: [2.763932  7.2360687]
Eigenvectors:
 [[ 0.85065085  0.52573115]
 [-0.52573115  0.85065085]]
L2 norm: 10.246951


Q3

In [ ]:
import torch

X = torch.tensor([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]
])

y_and = torch.tensor([0., 0., 0., 1.])

w = torch.randn(2, requires_grad=True)
b = torch.randn(1, requires_grad=True)

lr = 0.1

for epoch in range(1000):
    loss = 0
    # iterable tuple banave che
    for x, y in zip(X, y_and):
        z = torch.dot(w, x) + b
        y_hat = torch.sigmoid(z)
        loss += (y_hat - y) ** 2

    # w.grad and b.grad now contain ∂loss/∂w and ∂loss/∂b
    loss.backward()

    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
        w.grad.zero_()
        b.grad.zero_()

threshold = 0.5

print("AND Gate")
for x in X:
    prob = torch.sigmoid(torch.dot(w, x) + b)
    out = 1.0 if prob >= threshold else 0.0
    print(x.tolist(), "->", out, "(prob:", float(prob), ")")

AND Gate
[0.0, 0.0] -> 0.0 (prob: 0.004485994577407837 )
[0.0, 1.0] -> 0.0 (prob: 0.1331961452960968 )
[1.0, 0.0] -> 0.0 (prob: 0.1331855207681656 )
[1.0, 1.0] -> 1.0 (prob: 0.8397309184074402 )


In [ ]:
import torch

X = torch.tensor([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]
])

y_or = torch.tensor([0., 1., 1., 1.])

w = torch.randn(2, requires_grad=True)
b = torch.randn(1, requires_grad=True)

lr = 0.1

for epoch in range(1000):
    loss = 0
    for x, y in zip(X, y_or):
        z = torch.dot(w, x) + b
        y_hat = torch.sigmoid(z)
        loss += (y_hat - y) ** 2

    # w.grad and b.grad now contain ∂loss/∂w and ∂loss/∂b
    loss.backward()

    # prevents autograd from tracking updates
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
        w.grad.zero_() # stop from accumulating gradients
        b.grad.zero_()

threshold = 0.5

print("OR Gate")
for x in X:
    prob = torch.sigmoid(torch.dot(w, x) + b)
    out = 1.0 if prob >= threshold else 0.0
    print(x.tolist(), "->", out, "(prob:", float(prob), ")")

OR Gate
[0.0, 0.0] -> 0.0 (prob: 0.1321832835674286 )
[0.0, 1.0] -> 1.0 (prob: 0.9195904731750488 )
[1.0, 0.0] -> 1.0 (prob: 0.918760359287262 )
[1.0, 1.0] -> 1.0 (prob: 0.9988237023353577 )


Q4

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

X = torch.tensor([[0., 0.], [0., 1.], [1., 0.], [1., 1.]], dtype=torch.float32)
y = torch.tensor([[0.], [1.], [1.], [0.]], dtype=torch.float32)

# every trainable model must inherit from nn.Module as ena thi .parameters() and .train() jeva functions available thay
class XOR(nn.Module):
    def __init__(self):
        super(XOR, self).__init__()
        self.fc1 = nn.Linear(2, 2) # input to hidden layer
        self.fc2 = nn.Linear(2, 1) # hidden to output layer

    def forward(self, x):
        x = torch.relu(self.fc1(x)) # hidden layer activation
        x = torch.sigmoid(self.fc2(x)) # output activation
        return x

model = XOR()
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.02)

num_epochs = 10000
for epoch in range(num_epochs):
    outputs = model(X)
    loss = criterion(outputs, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step() # performs parameter update
    if (epoch + 1) % 1000 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

model.eval() # switches to evaluation mode
# dropout and batchnorm behave different
with torch.no_grad():
    predictions = model(X)
    rounded_predictions = (predictions >= 0.5).float()
    print("\nPredictions:")
    for i in range(len(X)):
        print(f"Input: {X[i].tolist()}, Output: {rounded_predictions[i].item()}")

Epoch [1000/10000], Loss: 0.0002
Epoch [2000/10000], Loss: 0.0001
Epoch [3000/10000], Loss: 0.0000
Epoch [4000/10000], Loss: 0.0000
Epoch [5000/10000], Loss: 0.0000
Epoch [6000/10000], Loss: 0.0000
Epoch [7000/10000], Loss: 0.0000
Epoch [8000/10000], Loss: 0.0000
Epoch [9000/10000], Loss: 0.0000
Epoch [10000/10000], Loss: 0.0000

Predictions:
Input: [0.0, 0.0], Output: 0.0
Input: [0.0, 1.0], Output: 1.0
Input: [1.0, 0.0], Output: 1.0
Input: [1.0, 1.0], Output: 0.0


Q5

In [46]:
X = torch.tensor([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.],
    [2., 3.],
    [4., 5.]
])

y = torch.tensor([
    [0.],
    [1.],
    [1.],
    [2.],
    [5.],
    [9.]
])

class NETWORK(nn.Module):
    def __init__(self):
        super(NETWORK, self).__init__()
        self.fc1 = nn.Linear(2, 2)
        self.fc2 = nn.Linear(2, 1) 
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        return self.fc2(x)   # raw value
       
model = NETWORK()
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.02)

for epoch in range(10000):
    outputs = model(x) # forward pass
    loss = criterion(outputs, y) # calculate loss
    optimizer.zero_grad() # zero the gradients
    loss.backward() # backpropagation
    optimizer.step() # update parameters

model.eval()
with torch.no_grad():
    user_x = input("Enter 2 numbers separated by space: ")
    user_x = torch.tensor([list(map(float, user_x.split()))])
    prediction = model(user_x)
    print("Predicted value:", prediction.item())

c:\Users\lenovo\anaconda3\envs\ai-gpu\lib\site-packages\torch\nn\modules\loss.py:608: UserWarning: Using a target size (torch.Size([6, 1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Predicted value: 2.878230094909668
